---
services:
  hugo:
    image: klakegg/hugo:ext-alpine
    command: server --buildDrafts --buildFuture --bind 0.0.0.0 --baseURL http://localhost:1313
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    environment:
      - HUGO_WATCH=true
      - HUGO_REFRESH_TIME=1
      - HUGO_ENVIRONMENT=development
      - HUGO_ENV=development
    working_dir: /src
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge