---
services:
  hugo:
    image: klakegg/hugo:ext-alpine
    command: server --buildDrafts --buildFuture --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    environment:
      - HUGO_WATCH=true
      - HUGO_REFRESH_TIME=1
    working_dir: /src
    networks:
      - blog-network

  hugo-build:
    image: klakegg/hugo:ext-alpine
    command: --minify
    volumes:
      - .:/src
    working_dir: /src
    profiles:
      - build
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
