baseURL = '/'
languageCode = 'en-us'
title = 'a2a.dons.dev'
theme = 'paper'
relativeURLs = false
canonifyURLs = true

[params]
  description = "Assistant to Agentic: A learning journey"
  author = "Don Smith"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
